### ISSUE TITLE
공통 UI 구현 

### ISSUE THREAD

**Issue by jaypedia** [Pullanner/pullanner-web#14]
# Description
- 화면에 공통적으로 표시되는 UI를 구현합니다. 

# Progress
- [x] #15
   - [x]  Pullanner 로고 클릭 시 메인 화면(로드맵)으로 이동
   - [x] 프로필 아이콘 클릭 시 로그인 안 되어 있을 시 로그인 팝업 / 로그인 되어 있을 시 마이페이지로 이동 
- [x] #16
   - [x] 4개의 항목 클릭 시 해당 페이지로 이동 (Roadmap, Journal, Dashboard, Community)
 
# 참고 이미지 
<img width="317" alt="image" src="https://github.com/Pullanner/pullanner-web/assets/85419343/a28162e7-61a1-4739-96f2-0058fa096981">
